
CREATE TABLE IF NOT EXISTS accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance             DECIMAL(19,2) CONSTRAINT balance_non_negative CHECK (balance >= 0),
    initial_balance     DECIMAL(19,2) CONSTRAINT initial_balance_non_negative CHECK (initial_balance >= 0),
    version BIGINT DEFAULT 0,
        CONSTRAINT max_balance_limit
        CHECK (balance <= initial_balance * 2.07)
);

CREATE TABLE IF NOT EXISTS users (
     id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username            VARCHAR(255) NOT NULL UNIQUE CHECK (length(trim(username)) >= 3 ),
     password            VARCHAR(3200) NOT NULL,
     date_of_birth       DATE NOT NULL,
     account_id          BIGINT UNIQUE NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
     version             BIGINT DEFAULT 0,
     CONSTRAINT unique_username UNIQUE (username)
);

CREATE TABLE user_roles (
    user_id             BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    roles               VARCHAR(255) NOT NULL CHECK (roles IN ('ROLE_USER')),
    PRIMARY KEY (user_id, roles)
);

CREATE TABLE IF NOT EXISTS email_data(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(320) NOT NULL UNIQUE CHECK (email ~* '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version BIGINT DEFAULT 0,
        CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS phone_data(
   id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   phone               VARCHAR(20) NOT NULL UNIQUE CHECK (phone ~ '^\+7\d{10}$'),
   user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
   version BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS black_list_refresh_tokens(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT,
    token_refresh       VARCHAR(1024),
    expire_at           TIMESTAMP
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_username ON users(username);
CREATE INDEX idx_email_data_user_id ON email_data(user_id);
CREATE INDEX idx_email_data_email ON email_data(email);
CREATE INDEX idx_phone_data_phone ON phone_data(phone);
CREATE INDEX idx_accounts_balance ON accounts(balance);
CREATE INDEX idx_accounts_initial_balance ON accounts(initial_balance);
CREATE INDEX idx_users_account_id ON users(account_id);
CREATE INDEX idx_users_username_trgm ON users USING GIN (LOWER(username) gin_trgm_ops);
CREATE INDEX idx_phone_data_user_id ON phone_data(user_id);

SET lock_timeout = '5s';

COMMENT ON CONSTRAINT max_balance_limit
ON accounts IS 'Баланс не может превышать 207% от начального депозита';