services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=account
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"