
CREATE TABLE IF NOT EXISTS users (
     id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username                VARCHAR(255) NOT NULL UNIQUE CHECK (length(trim(username)) >= 3 ),
     password            VARCHAR(3200) NOT NULL,
     version BIGINT DEFAULT 0
);

CREATE TABLE user_roles (
    user_id             BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    roles               VARCHAR(255) NOT NULL CHECK (roles IN ('ROLE_USER')),
    PRIMARY KEY (user_id, roles)
);

CREATE TABLE IF NOT EXISTS accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance             DECIMAL(19,2) CONSTRAINT balance_non_negative CHECK (balance >= 0),
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS email_data(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(320) NOT NULL UNIQUE CHECK (email ~* '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phone_data(
   id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   phone               VARCHAR(20) NOT NULL UNIQUE CHECK (phone ~ '^\+7\d{10}$'),
   user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
   version BIGINT DEFAULT 0
);
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_accounts_user_id ON accounts(user_id);
CREATE INDEX idx_email_data_user_id ON email_data(user_id);
CREATE INDEX idx_email_data_email ON email_data(email);
CREATE INDEX idx_phone_data_phone ON phone_data(phone);
CREATE INDEX idx_accounts_balance ON accounts(balance);
CREATE INDEX idx_users_username_trgm ON users USING GIN (username gin_trgm_ops);